dist: trusty

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer update --prefer-source --no-interaction --dev

script: vendor/bin/phpunit

matrix:
  fast_finish: true

notifications:
  on_success: never
  on_failure: always